default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  lane :beta do
     # Adjust the `build_type` and `flavor` params as needed to build the right APK for your setup
     gradle(
        task: 'assemble',
        build_type: 'debug'
     )
  end

  lane :hockeyapp do
     gradle(
	task: 'assemble',
	build_type: 'hockeyApp'
     )

     hockey(
  	api_token: "726d1c67dbc44ca8896b54ed265ed49f",
	apk: "app/build/outputs/apk/app-hockeyApp.apk",
	notes: "yay!",
	notify: "0"
     )
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
